### ISSUE TITLE
Error in admin view of DB Store handler table

### ISSUE THREAD

**Issue by bum2** [barseghyanartur/django-fobi#39]
When i go to /admin/fobi_contrib_plugins_form_handlers_db_store/savedformdataentry/ it throws me an error:
> 'super' object has no attribute 'queryset'

in "fobi/contrib/plugins/form_handlers/db_store/admin.py in queryset, line 47"

What can it be the reason? perhaps we have bad formed entries in that table? how to make the admin view to work again and delete some entries?

**Comment by barseghyanartur** [comment]
@bum2:

Upgrade to the latest version (0.6.8).

**Comment by bum2** [comment]
Upgraded to 0.6.8 but the error remains... is only the django admin view of the db-store handler that crashes with this env (it works good on local env). In the fobi upgrade is installed also django 1.10 and we are working with 1.8, so i had to install again django 1.8 after that. 
My theory is that the error is due the creation of instances of the SavedFormDataEntry class somewhat in our code, BEFORE the db-store handler is attached to the form. So, something weird we have only in our test server (not locally). Will be good to autodelete orphane entries on that table or prevent the error in some way to let admins delete test rows.
The affected line 47 of fobi/contrib/plugins/form_handlers/db_store/admin.py is:
>  queryset = super(SavedFormDataEntryAdmin, self).queryset(request)

and the error keeps the same:
> 'super' object has no attribute 'queryset'

**Comment by barseghyanartur** [comment]
@bum2:

Could you provide the full trace?

**Comment by bum2** [comment]
The error is gone when we reinstall fobi erasing the db tables. I think that if we don't create instances of the class SavedFormDataEntry without being a DB-Store handler attached to the form, then it will not fail the admin view. If it finds a strange row entry in that table, not related any DB_Store form handler, then it crashes. 
Of course we can live without fixing this, because is a weird case, and we will make sure to don't run the form before the handler is attached to it.

**Comment by barseghyanartur** [comment]
@bum2:

Thanks for the update! I'm closing it for now then. Feel free to reopen any time (please, provide a full trace then).
