### PR TITLE
Fix #14

### LINKED ISSUE #14: `django.utils.datastructures.SortedDict` removed in 1.9
As of 1.7 `django.utils.datastructures.SortedDict` was deprecated and was removed in 1.9.

    from django.utils.datastructures import SortedDict
        ImportError: cannot import name 'SortedDict'

### PR DESCRIPTION
**Pull request by jmsfwk**
Use collections.OrderedDict is django.utils.datastructures.SortedDict is
not available.

### CODE REVIEW

**Comment by barseghyanartur** [comment]
Great. I was planning to work on Django 1.9 compatibility soon and this part in particular. Thanks for the effort.
